const itemsSelect = [
    { "value": "beach", "label": "Beach" },
    { "value": "mountains", "label": "Mountains" },
    { "value": "city", "label": "City" },
    { "value": "nature", "label": "Nature" },
    { "value": "adventure", "label": "Adventure" },
    { "value": "road_trip", "label": "Road Trip" },
    { "value": "camping", "label": "Camping" },
    { "value": "hiking", "label": "Hiking" },
    { "value": "backpacking", "label": "Backpacking" },
    { "value": "island", "label": "Island" },
    { "value": "cruise", "label": "Cruise" },
    { "value": "historical", "label": "Historical" },
    { "value": "cultural", "label": "Cultural" },
    { "value": "food", "label": "Food & Gastronomy" },
    { "value": "nightlife", "label": "Nightlife" },
    { "value": "shopping", "label": "Shopping" },
    { "value": "romantic", "label": "Romantic" },
    { "value": "family", "label": "Family" },
    { "value": "solo", "label": "Solo Travel" },
    { "value": "luxury", "label": "Luxury" },
    { "value": "budget", "label": "Budget Travel" },
    { "value": "relaxation", "label": "Relaxation" },
    { "value": "photography", "label": "Photography" },
    { "value": "wildlife", "label": "Wildlife" },
    { "value": "water_sports", "label": "Water Sports" },
    { "value": "skiing", "label": "Skiing" },
    { "value": "desert", "label": "Desert" },
    { "value": "countryside", "label": "Countryside" },
    { "value": "wellness", "label": "Wellness" }
];
export default itemsSelect